#! /bin/sh
echo Setting up poetry environment
poetry install
pipx install .

echo installing SwiftBar Plugin
ln -s `which time_tracker` `defaults read com.ameba.SwiftBar PluginDirectory`/time_tracker.1m.py

echo installing launch agent
cat <<EOF > ~/Library/LaunchAgents/de.oefelein.time-tracker.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>de.oefelein.time-tracker</string>
	<key>ProgramArguments</key>
	<array>
		<string>$PWD/time-tracker-agent.py</string>
	</array>
    <key>KeepAlive</key>
    <true/>
	<key>WorkingDirectory</key>
	<string>$PWD</string>
</dict>
</plist>
EOF

launchctl load ~/Library/LaunchAgents/de.oefelein.time-tracker.plist

echo done!